#!/bin/bash

addrepos="yes"
function update() { sudo apt-get update && sudo apt-get upgrade -y --force-yes && sudo apt-get dist-upgrade -y --force-yes && sudo apt-get autoremove -y --force-yes && sudo apt-get autoclean; }
function install() { sudo apt-get install -fyuV "$@"; }
function script_failure() { echo -e "\n================================\nFAILURE `date -R`"; exit 1; }

if [ "addrepos" == "yes" ]; then
	sudo add-apt-repository ppa:bisigi/ppa
	sudo add-apt-repository ppa:tualatrix/ppa
	sudo add-apt-repository ppa:gloobus-dev/gloobus-preview
	sudo add-apt-repository ppa:am-monkeyd/nautilus-elementary-ppa
	sudo add-apt-repository ppa:tiheum/equinox
	sudo add-apt-repository ppa:elegant-gnome/ppa
	sudo add-apt-repository ppa:patrick-dessalle/ppa
fi

update

install git-core curl guake || {
	echo "Could not install cores."; script_failure;
}

install ubuntu-tweak libdvdread4 sun-java6-jre sun-java6-plugin gedit-plugins ubuntu-restricted-extras || {
	echo "Could not install ubuntu tweaks and required components."; script_failure;
}

install compiz compizconfig-settings-manager compiz-fusion-plugins-main compiz-fusion-plugins-extra librsvg2-common fusion-icon compizconfig-settings-manager || {
	echo "Could not install Compiz."; script_failure;
}

install vlc filezilla nano || {
	echo "Could not install other softwares"; script_failure;
}

install build-essential python-setuptools autoconf bison build-essential libapr1-dev libaprutil1-dev libcurl4-openssl-dev libid3-3.8.3-dev libmysqlclient16 libmysqlclient16-dev libreadline6 libreadline6-dev libsqlite3-0 libsqlite3-dev libssl-dev libxml2-dev libxslt-dev libyaml-dev zlib1g zlib1g-dev libapache2-mod-php5 libapache2-mod-auth-mysql redis-server libxslt1.1 libxslt1-dev libxml2 libmagickwand-dev

install git-core git-svn subversion

install curl imagemagick openssl openssh-client openssh-server

install apache2 apache2-threaded-dev mysql-client mysql-common mysql-server sqlite3 php5 php5-mysql php5-cli php5-dev php-pear php5-gd php5-mcrypt php5-imagick php5-curl php5-xmlrpc php5-xsl php5-mhash phpmyadmin

update

pear config-set php_ini /etc/php5/apache2/php.ini
pecl config-set php_ini /etc/php5/apache2/php.ini

sudo pear channel-update pear.php.net
sudo pear upgrade-all
sudo pear install HTML_QuickForm2-0.5.0 HTML_Common2 HTML_Template_Sigma

sudo pecl install xdebug

wget http://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
tar zxvf ioncube_loaders_lin_x86.tar.gz
sudo mv ioncube /usr/local/lib/
echo "zend_extension=/usr/local/ioncube/ioncube_loader_lin_5.3.so" | sudo tee /etc/php5/conf.d/ioncube.ini

sudo a2enmod vhost_alias rewrite ssl suexec include proxy proxy_http

update

echo "SUCCESS"
